version: '3'

services:
  sbfrontend:
    build:
      context: ./sbfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_URI=mongodb://stbankdb:27017/dbname  # Changed MONGO_URI to DB_URI for consistency
    depends_on:
      - stbankdb

  stbankdb:
    image: mongo:latest
    container_name: stbankdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: