version: '3'

services:
  sbfrontend:
    build:
      context: ./sbfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://stbankdb:27017/dbname
    depends_on:
      - stbankdb

  stbankdb:
    image: mongo:latest
    container_name: stbankdb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: